### ISSUE TITLE
There is no way to stop the cluster

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#144]
stop-cluster calls /kill, which results in the service restarting kotekan. We need a separate kill (used for restart) and stop.

**Comment by andrerenard** [comment]
At the `coco` level yes we need different endpoints.  However the kotekan call should only ever be `/kill` to exit (and cause a binary restart).   Currently `/stop` on `kotekan` should be considered broken.

**Comment by nritsche** [comment]
@andrerenard Oh, so we are actually good? `/kill` will lead to a restart without loading a new config and that's what we consider a "stopped" cluster.

**Comment by andrerenard** [comment]
Yes.  The problem we had (from what I can tell) was the coco kept sending new configs after the kotekan instance restarted.

**Comment by nritsche** [comment]
Thanks. I've made a new issue: #145
