### ISSUE TITLE
Switch from `umsgpack` to `msgpack`

### ISSUE THREAD

**Issue by jrs65** [chime-experiment/coco#170]
We should try and move back to the standard `msgpack` library we use elsewhere, but first we need to check that the serialisation is exactly the same as in kotekan (which it is for `umsgpack`).

**Comment by jrs65** [comment]
We should try and move back to the standard `msgpack` library we use elsewhere, but first we need to check that the serialisation is exactly the same as in kotekan (which it is for `umsgpack`).

**Comment by nritsche** [comment]
Done in a365d1e64f19e7c9a41cea0a4cd2411ca92e25e1
