### ISSUE TITLE
Coco crashes with KeyError after state reset

### ISSUE THREAD

**Issue by jrs65** [chime-experiment/coco#177]
This happens because the watchdog scheduler checks for the presence of `cluster_running` and `receiver_running` keys in the state, but they don't exist after a reset.

**Comment by nritsche** [comment]
1. There's a bug between `state` and `scheduler` where the state re-raises the `KeyError` as a `RuntimeError`, but the scheduler still tries to catch the `KeyError`. This is an easy fix. I propose to use an `InternalCocoError` between state and scheduler.
2. What should really happen with this part of the state during a state-reset? In this particular example, the `*_running` should be excluded from the reset. We could add a mandatory parameter to `reset-state` that tells it which part of the state to reset.
