### ISSUE TITLE
Add command to backup and restore state

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#192]
Coco writes it's state to a file in `/var/lib/coco/state`. During deployment weeks and testing, it would be useful to have a way to make coco store a named state and later recover it. To test feasibility, we are going to do this manually by moving around files in the 2020.04 deployment.

**Comment by nritsche** [comment]
@andrerenard @jrs65 Did we do this?

**Comment by andrerenard** [comment]
No I don't think we did.

**Comment by nritsche** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [coco monthly maintanance](https://trello.com/c/vMMyeOsv/7-coco-monthly-maintanance)
