### ISSUE TITLE
/var/lib/coco/state ended up as a file

### ISSUE THREAD

**Issue by jrs65** [chime-experiment/coco#220]
Somehow the path to coco's state end up having a file their rather than a directory and so it refused to start. Not sure exactly how, this was after deploying it via the coco playbook in ch_ansible, and a few reset states.

**Comment by nritsche** [comment]
I can't find any reason why this would happen :shrug:

**Comment by nritsche** [comment]
Please reopen if this happens again or if we have any details on it.
