### ISSUE TITLE
Add HFB receiver system to coco

### ISSUE THREAD

**Issue by james-s-willis** [chime-experiment/coco#227]

**Comment by james-s-willis** [comment]
See https://github.com/chime-experiment/ch_ansible/pull/228

**Comment by mondana** [comment]
can I close this? @james-s-willis

**Comment by james-s-willis** [comment]
@mondana yeah this is done now.

**Comment by nritsche** [comment]
Closed via https://github.com/chime-experiment/ch_ansible/pull/228
