### ISSUE TITLE
Start warm-cluster on fpga_master connection failure.

### ISSUE THREAD

**Issue by andrerenard** [chime-experiment/coco#239]
It has been proposed to add a new endpoint to coco which would stop the cluster and then restart it in `keep-warm` mode.  This new mode would be activated by one of the three FPGA check failures: frame0_time, frequency_map, and dataset_id.  

This would prevent the GPU cluster from getting cold (and creating air locks in the CHx40s) if there is a problem with the FPGA, or some other problem communicating with fpga_master.

**Comment by anjakefala** [comment]
I went to create this and then noticed there seems to already be a `warm-the-cluster` endpoint, which is almost identical except it has `forward: start` instead of `forward: kill`. It was created by Rick on 2020-11-16.

28061c43ea184ef19d1efc1dc35c2faa65f268e1

**Comment by jrs65** [comment]
Indeed there is, but I didn't think we could get away with using this.

I *think* we will probably need two endpoints to do this. The existing one is to allow the user to cleanly put things into the warming state, the one I put above is designed to immediately stop the running and then enter warming state, but only in case of a failure in another endpoint.

The only way it might be avoided is if there is a way to chain endpoints within the failure clause of an existing endpoint, i.e. if in the `gps-time` endpoint you can make two successive calls in the `on_failure` block.
