### ISSUE TITLE
Add endpoint: status

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#44]
status_kotekan_master - depends on #41

- returns the complete state
- kotekan_nodes: GPU nodes
- unique_md5sums
- node_md5sums a dict with `{node: md5sum, ...}`
- receiver_nodes
- kotekan_versions
  ```
  kotekan_version : dict-type
            { "node_name" : {"available_processes": ["p1","p2", ... "pN"],
                             "branch": "master",
                             "cmake_build_settings" : "BUILD_OPTIONS",
                             "git_commit_hash": "b1ce8aecf",
                             "kotekan_version": "2.3"
                            }
  ```
- blacklist_nodes: list of names
- connection_error_nodes: `(time.ctime(), {"node_name": "HTTPError"})`
- watchdog_status:
  - watchdog_enabled
  - watchdog_interval
  - watchdog_cycles
  - watchdog_stats
  - update_moratorium
  - array_sync
  - km_sync
- gps_status:
  - gps_server
  - gps_status
  - gps_time
- calibration_broker_status:
  - calibration_tag:  self.cal_broker_gain_tag
  - calibration_start_time: self.cal_broker_gain_update_time
  - correlator_bad_inputs": self.correlator_bad_inputs
  - cylinder_bad_inputs": self.cylinder_bad_inputs
  - bad_inputs_tag": self.bad_inputs_tag
  - bad_inputs_update_time": self.bat_inputs_update_time
- frb_status
  - gains_dir: _config.frb_gain.frb_gain_dir
  - gains_dir_update_time: self.frb_gains_dir_update_time
  - ew_spacing: _config.gpu.gpu_0.ew_spacing
  - ew_spacing_update_time": self.ew_spacing_update_time
  - ns_extent: _config.gpu.gpu_0.northmost_beam
  - ns_extent_update_time: self.ns_extent_update_time
- pulsar_status
  - gain_dirs: _config.pulsar_gain.pulsar_gain_dir
  - gain_update_time: self.pulsar_gains_dirs_update_time
  - last_beam_update_time: self.pulsar_update_time
  - ra: _config.gpu.gpu_0.source_ra
  - dec: _config.gpu.gpu_0.source_dec
  - scaling: _config.gpu.gpu_0.psr_scaling
- cosmology_status
  - rfi_zeroing: str(_config.rfi_masking.toggle.rfi_zeroing
   - pulsar_gating: str(_config.updatable_config.gating)
- git_version": self.git_version
- start_time:  time.strftime("%Y/%m/%d %H:%M:%S", time.localtime(self.start_time)

**Comment by tristpinsm** [comment]
I'm working on implementing this and I'm going to track what items I've put in here.

- [ ] returns the complete state
- [ ] kotekan_nodes: GPU nodes
    - coco `status-cluster` 
- [ ] receiver_nodes
    - coco 'status-receiver`
- [ ] unique_md5sums
    - *I'm not sure what this is or how to produce it.*
- [ ] node_md5sums a dict with {node: md5sum, ...}
    - forward `config_md5sum`
- [ ] kotekan_versions
    - coco `version-receiver`
   - coco `version-cluster`
- [ ] kotekan_version : dict-type
    - *redundant with kotekan_versions*
```
          { "node_name" : {"available_processes": ["p1","p2", ... "pN"],
                           "branch": "master",
                           "cmake_build_settings" : "BUILD_OPTIONS",
                           "git_commit_hash": "b1ce8aecf",
                           "kotekan_version": "2.3"
                          }
```
- [ ] blacklist_nodes: list of names
    - coco `blacklist`
- [ ] connection_error_nodes: (time.ctime(), {"node_name": "HTTPError"})
- [ ] watchdog_status:
    - [ ] watchdog_enabled
    - [ ] watchdog_interval
    - [ ] watchdog_cycles
    - [ ] watchdog_stats
    - *deprecated*
- [ ] update_moratorium
    - *deprecated*
- [ ] array_sync
    - *deprecated*
- [ ] km_sync
    - *deprecated*
- [ ] gps_status:
    - [ ] gps_server
    - [ ] gps_status
    - [ ] gps_time
    - *included in state*
- [ ] calibration_broker_status:
    - [ ] calibration_tag: self.cal_broker_gain_tag
    - [ ] calibration_start_time: self.cal_broker_gain_update_time
    - [ ] correlator_bad_inputs": self.correlator_bad_inputs
    - [ ] cylinder_bad_inputs": self.cylinder_bad_inputs
    - [ ] bad_inputs_tag": self.bad_inputs_tag
    - [ ] bad_inputs_update_time": self.bat_inputs_update_time
    - *included in state*
- [ ] frb_status
    - [ ] gains_dir: _config.frb_gain.frb_gain_dir
    - [ ] gains_dir_update_time: self.frb_gains_dir_update_time
    - [ ] ew_spacing: _config.gpu.gpu_0.ew_spacing
    - [ ] ew_spacing_update_time": self.ew_spacing_update_time
    - [ ] ns_extent: _config.gpu.gpu_0.northmost_beam
    - [ ] ns_extent_update_time: self.ns_extent_update_time
- [ ] pulsar_status
    - [ ] gain_dirs: _config.pulsar_gain.pulsar_gain_dir
    - [ ] gain_update_time: self.pulsar_gains_dirs_update_time
    - [ ] last_beam_update_time: self.pulsar_update_time
    - [ ] ra: _config.gpu.gpu_0.source_ra
    - [ ] dec: _config.gpu.gpu_0.source_dec
    - [ ] scaling: _config.gpu.gpu_0.psr_scaling
    - [ ] cosmology_status
    - [ ] rfi_zeroing: str(_config.rfi_masking.toggle.rfi_zeroing
    - [ ] pulsar_gating: str(_config.updatable_config.gating)
- [ ] git_version": self.git_version
- [ ] start_time: time.strftime("%Y/%m/%d %H:%M:%S", time.localtime(self.start_time)
