### ISSUE TITLE
Add endpoint: /update-frb-gain-dirs

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#58]
value:
```
frb_gain_dir: str
```
- creates a (current) timestamp and saves it in state (used by /status): `timestamp/frb-gain-dir`
- saves the value in state (used by /status): `cluster/frb_gain/frb_gain_dir`

**Comment by nritsche** [comment]
@cherryng  @shinybrar  Does anything use `/status-kotekan-master` to get `frb_status/gains_dir_update_time`?

**Comment by cherryng** [comment]
Davor said: we have a Prometheus check for `/status-kotekan-master` returning OK, and an alert if it does not.
