### ISSUE TITLE
Add argument to endpoint call: hosts

### ISSUE THREAD

**Issue by nritsche** [chime-experiment/coco#76]
#75 needs an option to override the configured group with a list of hosts (in a single call) is needed.

**Comment by tristpinsm** [comment]
Why does `RequestForwarder` have `call` method in addition to `forward`? It seems to only be used inside `Endpoint`, where it would be equivalent to just call `self.call(...)`

**Comment by nritsche** [comment]
That's because the endpoints don't know the other endpoints. The forwarder knows them all and is known by all endpoints. So if an endpoint wants to call an endpoint (e.g. `before`, `after`, ...) it has to do so through the forwarder.

**Comment by tristpinsm** [comment]
ah, of course that makes sense
